<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Note If the email does not arrive, please_53fafa</name>
   <tag></tag>
   <elementGuidId>70e5ef13-d9db-4c66-b75d-46d699e0f388</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.oxd-text.oxd-text--p.orangehrm-card-note.orangehrm-card-note--background.orangehrm-forgot-password-card-note</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/p[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>1a525814-5b4a-4970-b035-466b98ad5d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-text oxd-text--p orangehrm-card-note orangehrm-card-note--background orangehrm-forgot-password-card-note</value>
      <webElementGuid>b01490d0-25b2-4d43-a1bd-1bcf440f3e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Note: If the email does not arrive, please contact your OrangeHRM Administrator.</value>
      <webElementGuid>5139d597-3357-4e43-b604-067bb3263dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;orangehrm-forgot-password-container&quot;]/div[@class=&quot;orangehrm-forgot-password-wrapper&quot;]/div[@class=&quot;orangehrm-card-container&quot;]/p[@class=&quot;oxd-text oxd-text--p orangehrm-card-note orangehrm-card-note--background orangehrm-forgot-password-card-note&quot;]</value>
      <webElementGuid>13f26e3a-603d-456f-a9d8-06f5e5a85f0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/p[3]</value>
      <webElementGuid>b643d0d9-c72e-4ba8-abb3-b404d56d98da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OrangeHRM, Inc'])[1]/preceding::p[4]</value>
      <webElementGuid>62611679-c892-4c8c-97a6-1e6437819fac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]</value>
      <webElementGuid>dc927ed0-b6ec-4b60-9fb0-e60b60a3417c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Note: If the email does not arrive, please contact your OrangeHRM Administrator.' or . = 'Note: If the email does not arrive, please contact your OrangeHRM Administrator.')]</value>
      <webElementGuid>63a8cf64-e20d-443c-baf9-5daf91e81049</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
